server:
  port: 8086
  forward-headers-strategy: framework
spring:
  application:
    name: sc-admin-server
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@config-server:8888
