server:
  port: 8086
  forward-headers-strategy: framework
eureka:
  client:
    enabled: false
spring:
  application:
    name: sc-admin-server
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/sc
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/sc
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-id: admin-service
            client-secret: 8wDlmDewQ5k48xjAtns6RlcwKu1Nb3LS
            authorization-grant-type: client_credentials
            scope:
              - metrics
          login:
            provider: keycloak
            client-id: admin-service
            client-secret: 8wDlmDewQ5k48xjAtns6RlcwKu1Nb3LS
            scope:
              - openid
              - metrics
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus