server:
  port: 8087
  forward-headers-strategy: framework
spring:
  application:
    name: sc-api-gateway
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@config-server:8888