server:
  port: 8084
  forward-headers-strategy: framework
aeresfiru:
  services:
    catalogue:
      uri: http://localhost:8081
eureka:
  client:
    enabled: false
spring:
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: manager-app
          service-host-type: ip
        url: http://localhost:8086
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/sc
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/sc
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: dpVioAWGz7zbiDqAeYh9M8oxsKtjZTOf
            authorization-grant-type: authorization_code
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
          metrics:
            provider: keycloak
            client-id: manager-app-metrics-client
            client-secret: Y4C6Diivzbgwn41jsSHqNqOLRI0hycG8
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'