server:
  port: 8086
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
spring:
  application:
    name: sc-admin-server
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/sc
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/sc
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-id: admin-service
            client-secret: 8wDlmDewQ5k48xjAtns6RlcwKu1Nb3LS
            authorization-grant-type: client_credentials
            scope:
              - openid
              - metrics
              - microprofile-jwt
          discovery:
            provider: keycloak
            client-id: admin-service
            client-secret: 8wDlmDewQ5k48xjAtns6RlcwKu1Nb3LS
            authorization-grant-type: client_credentials
            scope:
              - discovery
          login:
            provider: keycloak
            client-id: admin-service
            client-secret: 8wDlmDewQ5k48xjAtns6RlcwKu1Nb3LS
            scope:
              - openid
              - metrics
              - microprofile-jwt
