aeresfiru:
  services:
    admin:
      registration-id: keycloak
server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    username: catalogue
    password: catalogue
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    show-sql: true
  flyway:
    schemas:
      - public
      - catalogue
  boot:
    admin:
      client:
        url: http://localhost:8086
        instance:
          name: catalogue-service
          service-host-type: ip
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/sc
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/sc
        registration:
          keycloak:
            client-id: catalogue-service-metrics-client
            client-secret: nxrIae4d2k8whceCEQYVgarBbln6ai7C
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
springdoc:
  swagger-ui:
    oauth:
      client-id: catalogue-service-swagger-ui
      use-pkce-with-authorization-code-grant: true
    path: /swagger-ui-catalogue
    url: /catalogue-api.yaml
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
