server:
  port: 8761
  forward-headers-strategy: framework
spring:
  application:
    name: sc-eureka-server
  config:
    import: 'configserver:'
  cloud:
    config:
      uri: http://config:config@localhost:8888