server:
  port: 8085
  forward-headers-strategy: framework
spring:
  application:
    name: sc-feedback-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@config-server:8888