server:
  forward-headers-strategy: native
  port: 8085
spring:
  application:
    name: sc-feedback-service
  config:
    import: 'configserver:'
  cloud:
    config:
      uri: http://config:config@localhost:8888