server:
  port: 8083
aeresfiru:
  services:
    catalogue:
      uri: http://localhost:8081
    feedback:
      uri: http://localhost:8085
eureka:
  client:
    enabled: false
spring:
  application:
    name: sc-customer-application
  boot:
    admin:
      client:
        enabled: true
        instance:
          service-host-type: ip
          name: customer-app
        url: http://localhost:8086
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/sc
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/sc
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-id: customer-app
            client-secret: G1ze2jJUa6ZcAuGKWGfqA73DmRKyAAjA
            authorization-grant-type: authorization_code
            scope:
              - openid
              - view_catalogue
          metrics:
            provider: keycloak
            client-id: customer-app-metrics-client
            client-secret: sSBjtJnkYR2cVRpOdBLPlUuE34ZMCKpy
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'