server:
  port: 8083
  forward-headers-strategy: framework
spring:
  application:
    name: sc-customer-app
  config:
    import: 'configserver:'
  cloud:
    config:
      uri: http://config:config-password@config-server:8888